[project]
name = "ssserve"
version = "0.3.3"
dynamic = ["description"]
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["click>=8.0"]
license = "MIT"

[project.scripts]
ssserve = "ssserve.cli:main"

[build-system]
requires = ["setuptools>=83.0.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["ssserve"]

[dependency-groups]
dev = [
    "pytest>=8",
    "psutil>=6",
    "asv>=0.6.5",
    "setuptools>=83.0.0",
]
